name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          # Use version from root package.json's packageManager to avoid mismatch
          package_json_file: package.json
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile=false
      - name: Build
        run: pnpm build
      - name: Unit tests (Vitest)
        run: pnpm --filter @syntopia/app test
      - name: Install Playwright browsers
        run: pnpm --filter @syntopia/app e2e:install
      - name: E2E tests (Playwright)
        run: pnpm --filter @syntopia/app e2e
